from snakemake.io import glob_wildcards,strip_wildcard_constraints,get_wildcard_names
import snakebids

configfile: 'config.yml'


glob_bids = glob_wildcards(config['bids_subject'])

subjects = glob_bids.subject

test_subjects = list(set(config.get('test_subjects',[])) & set(subjects))
if len(test_subjects) > 0:
    subjects = test_subjects


rule all:
    input:
        'fmriprep/dataset_description.json',
        expand('hippunfold/sub-{subject}',subject=subjects),
        expand('freesurfer/sub-{subject}',subject=subjects)

include: 'rules/freesurfer.smk'
include: 'rules/fmriprep.smk'
include: 'rules/hippunfold.smk'




